application: anki
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /templates
  static_dir: templates

- url: /.*
  script: anki.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

